name: Deploy

on:
    push:
        branches: [ feat/actions ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              uses: appleboy/ssh-action@v0.1.2
              env:
                token: ${{ secrets.ACCESS_TOKEN }}
              with:
                host: ${{secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                envs: token
                script: |
                    git clone https://jmularski:$token@github.com/UCLComputerScience/COMP0016_2020_21_Team18
                    cd ./COMP0016_2020_21_Team18
                    npm install
                    pm2 start deploy.config.js
