name: Test

on:
    push:
        branches:
            - feat/tests
    pull_request:
        branches:
            - master
            - development
            - feat/tests

jobs:
    test:
        name: Jest Annotations & Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install modules
              run: yarn
            - name: Install cypress
              run: yarn install -g cypress
            - name: Run tests
              run: yarn jest --json --outputFile="jest.results.json" --passWithNoTests
            - name: Run E2E tests
              run: cd ./tests/e2e && cypress run